#!/bin/bash

function showMissing {
	echo "rbac: missing operand."
	echo "Try: 'rbac --help' for more information."
}

function confirm {
	read -p "Continue (y/n)? " choice
	case "$choice" in
		y|Y ) 
			echo "yes"
			;;
		n|N ) 
			echo "no"
			exit
			;;
		* ) 
			echo "rbac: invalid confirmation."
			exit
			;;
	esac
}

function confirmUser {
	read -p "Username? " choice
	if [ $choice != $USER ]
	then
		echo "rbac: invalid confirmation."
		exit
	fi	

}

function help {
	echo "Usage: rbac [COMMAND]"
	echo -e "Create and remove users.\n"
	echo "-c, --create			create user"
	echo "-r, --remove			remove user"
	echo "--help				display this help and exit"
}	

function create {
	confirm
	echo "create"
}

function remvoe {
	confirm
	confirmUser
	echo "remove"
}

if [ $# -lt 1 ]
then
	showMissing
fi

while [ "$1" != "" ] 
do
	case "$1" in

		"-c" | "--create")
			create
			;;
		"-r" | "--remove")
			remove
			;;
		"--help")	
			help
			;;
		*)
			echo "rbac: invalid command."
			echo "Try: 'rbac --help' for more information."
	esac
	shift
done
